# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.soil_profile_update import SoilProfileUpdate

class TestSoilProfileUpdate(unittest.TestCase):
    """SoilProfileUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SoilProfileUpdate:
        """Test SoilProfileUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SoilProfileUpdate`
        """
        model = SoilProfileUpdate()
        if include_optional:
            return SoilProfileUpdate(
                area_id = '',
                aspect = '',
                coord_x = 1.337,
                coord_y = 1.337,
                coord_z = 1.337,
                description_horizon = None,
                gradient = '',
                lythology_surficial_deposit = '',
                name = '',
                parent_material = 1.337,
                photo = '',
                soil_diagram = '',
                soil_type_id = '',
                topography = '',
                vegetation_type = '',
                weather = ''
            )
        else:
            return SoilProfileUpdate(
        )
        """

    def testSoilProfileUpdate(self):
        """Test SoilProfileUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
