# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_one_area(self) -> None:
        """Test case for create_one_area

        Create one area
        """
        pass

    def test_create_one_assignment__sensor_profile(self) -> None:
        """Test case for create_one_assignment__sensor_profile

        Create one assignment (sensor profile)
        """
        pass

    def test_create_one_channel__instrument_experiment(self) -> None:
        """Test case for create_one_channel__instrument_experiment

        Create one channel (instrument experiment)
        """
        pass

    def test_create_one_experiment__lab_instrument(self) -> None:
        """Test case for create_one_experiment__lab_instrument

        Create one experiment (lab instrument)
        """
        pass

    def test_create_one_gnss_recording(self) -> None:
        """Test case for create_one_gnss_recording

        Create one GNSS recording
        """
        pass

    def test_create_one_plot(self) -> None:
        """Test case for create_one_plot

        Create one plot
        """
        pass

    def test_create_one_profile__sensor(self) -> None:
        """Test case for create_one_profile__sensor

        Create one profile (sensor)
        """
        pass

    def test_create_one_project(self) -> None:
        """Test case for create_one_project

        Create one project
        """
        pass

    def test_create_one_sample__plot(self) -> None:
        """Test case for create_one_sample__plot

        Create one sample (plot)
        """
        pass

    def test_create_one_sensor(self) -> None:
        """Test case for create_one_sensor

        Create one sensor
        """
        pass

    def test_create_one_soil_profile(self) -> None:
        """Test case for create_one_soil_profile

        Create one soil profile
        """
        pass

    def test_create_one_soil_type(self) -> None:
        """Test case for create_one_soil_type

        Create one soil type
        """
        pass

    def test_create_one_transect(self) -> None:
        """Test case for create_one_transect

        Create one transect
        """
        pass

    def test_delete_many_areas(self) -> None:
        """Test case for delete_many_areas

        Delete many areas
        """
        pass

    def test_delete_many_assignments__sensor_profile(self) -> None:
        """Test case for delete_many_assignments__sensor_profile

        Delete many assignments (sensor profile)
        """
        pass

    def test_delete_many_channels__instrument_experiment(self) -> None:
        """Test case for delete_many_channels__instrument_experiment

        Delete many channels (instrument experiment)
        """
        pass

    def test_delete_many_experiments__lab_instrument(self) -> None:
        """Test case for delete_many_experiments__lab_instrument

        Delete many experiments (lab instrument)
        """
        pass

    def test_delete_many_gnss_recordings(self) -> None:
        """Test case for delete_many_gnss_recordings

        Delete many GNSS recordings
        """
        pass

    def test_delete_many_plots(self) -> None:
        """Test case for delete_many_plots

        Delete many plots
        """
        pass

    def test_delete_many_profiles__sensor(self) -> None:
        """Test case for delete_many_profiles__sensor

        Delete many profiles (sensor)
        """
        pass

    def test_delete_many_projects(self) -> None:
        """Test case for delete_many_projects

        Delete many projects
        """
        pass

    def test_delete_many_samples__plot(self) -> None:
        """Test case for delete_many_samples__plot

        Delete many samples (plot)
        """
        pass

    def test_delete_many_sensors(self) -> None:
        """Test case for delete_many_sensors

        Delete many sensors
        """
        pass

    def test_delete_many_soil_profiles(self) -> None:
        """Test case for delete_many_soil_profiles

        Delete many soil profiles
        """
        pass

    def test_delete_many_soil_types(self) -> None:
        """Test case for delete_many_soil_types

        Delete many soil types
        """
        pass

    def test_delete_many_transects(self) -> None:
        """Test case for delete_many_transects

        Delete many transects
        """
        pass

    def test_delete_one_area(self) -> None:
        """Test case for delete_one_area

        Delete one area
        """
        pass

    def test_delete_one_assignment__sensor_profile(self) -> None:
        """Test case for delete_one_assignment__sensor_profile

        Delete one assignment (sensor profile)
        """
        pass

    def test_delete_one_channel__instrument_experiment(self) -> None:
        """Test case for delete_one_channel__instrument_experiment

        Delete one channel (instrument experiment)
        """
        pass

    def test_delete_one_experiment__lab_instrument(self) -> None:
        """Test case for delete_one_experiment__lab_instrument

        Delete one experiment (lab instrument)
        """
        pass

    def test_delete_one_gnss_recording(self) -> None:
        """Test case for delete_one_gnss_recording

        Delete one GNSS recording
        """
        pass

    def test_delete_one_plot(self) -> None:
        """Test case for delete_one_plot

        Delete one plot
        """
        pass

    def test_delete_one_profile__sensor(self) -> None:
        """Test case for delete_one_profile__sensor

        Delete one profile (sensor)
        """
        pass

    def test_delete_one_project(self) -> None:
        """Test case for delete_one_project

        Delete one project
        """
        pass

    def test_delete_one_sample__plot(self) -> None:
        """Test case for delete_one_sample__plot

        Delete one sample (plot)
        """
        pass

    def test_delete_one_sensor(self) -> None:
        """Test case for delete_one_sensor

        Delete one sensor
        """
        pass

    def test_delete_one_soil_profile(self) -> None:
        """Test case for delete_one_soil_profile

        Delete one soil profile
        """
        pass

    def test_delete_one_soil_type(self) -> None:
        """Test case for delete_one_soil_type

        Delete one soil type
        """
        pass

    def test_delete_one_transect(self) -> None:
        """Test case for delete_one_transect

        Delete one transect
        """
        pass

    def test_delete_sensor_data(self) -> None:
        """Test case for delete_sensor_data

        Delete sensor data
        """
        pass

    def test_get_all_areas(self) -> None:
        """Test case for get_all_areas

        Get all areas
        """
        pass

    def test_get_all_assignments__sensor_profile(self) -> None:
        """Test case for get_all_assignments__sensor_profile

        Get all assignments (sensor profile)
        """
        pass

    def test_get_all_channels__instrument_experiment(self) -> None:
        """Test case for get_all_channels__instrument_experiment

        Get all channels (instrument experiment)
        """
        pass

    def test_get_all_experiments__lab_instrument(self) -> None:
        """Test case for get_all_experiments__lab_instrument

        Get all experiments (lab instrument)
        """
        pass

    def test_get_all_gnss_recordings(self) -> None:
        """Test case for get_all_gnss_recordings

        Get all GNSS recordings
        """
        pass

    def test_get_all_plots(self) -> None:
        """Test case for get_all_plots

        Get all plots
        """
        pass

    def test_get_all_profiles__sensor(self) -> None:
        """Test case for get_all_profiles__sensor

        Get all profiles (sensor)
        """
        pass

    def test_get_all_projects(self) -> None:
        """Test case for get_all_projects

        Get all projects
        """
        pass

    def test_get_all_samples__plot(self) -> None:
        """Test case for get_all_samples__plot

        Get all samples (plot)
        """
        pass

    def test_get_all_sensors(self) -> None:
        """Test case for get_all_sensors

        Get all sensors
        """
        pass

    def test_get_all_soil_profiles(self) -> None:
        """Test case for get_all_soil_profiles

        Get all soil profiles
        """
        pass

    def test_get_all_soil_types(self) -> None:
        """Test case for get_all_soil_types

        Get all soil types
        """
        pass

    def test_get_all_transects(self) -> None:
        """Test case for get_all_transects

        Get all transects
        """
        pass

    def test_get_filtered_data(self) -> None:
        """Test case for get_filtered_data

        Get filtered experiment (lab instrument) data
        """
        pass

    def test_get_one(self) -> None:
        """Test case for get_one

        Get one profile (sensor)
        """
        pass

    def test_get_one_area(self) -> None:
        """Test case for get_one_area

        Get one area
        """
        pass

    def test_get_one_assignment__sensor_profile(self) -> None:
        """Test case for get_one_assignment__sensor_profile

        Get one assignment (sensor profile)
        """
        pass

    def test_get_one_channel__instrument_experiment(self) -> None:
        """Test case for get_one_channel__instrument_experiment

        Get one channel (instrument experiment)
        """
        pass

    def test_get_one_experiment__lab_instrument(self) -> None:
        """Test case for get_one_experiment__lab_instrument

        Get one experiment (lab instrument)
        """
        pass

    def test_get_one_gnss_recording(self) -> None:
        """Test case for get_one_gnss_recording

        Get one GNSS recording
        """
        pass

    def test_get_one_plot(self) -> None:
        """Test case for get_one_plot

        Get one plot
        """
        pass

    def test_get_one_project(self) -> None:
        """Test case for get_one_project

        Get one project
        """
        pass

    def test_get_one_sample__plot(self) -> None:
        """Test case for get_one_sample__plot

        Get one sample (plot)
        """
        pass

    def test_get_one_sensor(self) -> None:
        """Test case for get_one_sensor

        Get one sensor
        """
        pass

    def test_get_one_soil_profile(self) -> None:
        """Test case for get_one_soil_profile

        Get one soil profile
        """
        pass

    def test_get_one_soil_type(self) -> None:
        """Test case for get_one_soil_type

        Get one soil type
        """
        pass

    def test_get_one_transect(self) -> None:
        """Test case for get_one_transect

        Get one transect
        """
        pass

    def test_get_raw_data(self) -> None:
        """Test case for get_raw_data

        Get raw experiment (lab instrument) data
        """
        pass

    def test_get_summary_data(self) -> None:
        """Test case for get_summary_data

        Get summary data for experiment (lab instrument)
        """
        pass

    def test_get_ui_config(self) -> None:
        """Test case for get_ui_config

        """
        pass

    def test_healthz(self) -> None:
        """Test case for healthz

        """
        pass

    def test_update_one_area(self) -> None:
        """Test case for update_one_area

        Update one area
        """
        pass

    def test_update_one_assignment__sensor_profile(self) -> None:
        """Test case for update_one_assignment__sensor_profile

        Update one assignment (sensor profile)
        """
        pass

    def test_update_one_channel__instrument_experiment(self) -> None:
        """Test case for update_one_channel__instrument_experiment

        Update one channel (instrument experiment)
        """
        pass

    def test_update_one_experiment__lab_instrument(self) -> None:
        """Test case for update_one_experiment__lab_instrument

        Update one experiment (lab instrument)
        """
        pass

    def test_update_one_gnss_recording(self) -> None:
        """Test case for update_one_gnss_recording

        Update one GNSS recording
        """
        pass

    def test_update_one_plot(self) -> None:
        """Test case for update_one_plot

        Update one plot
        """
        pass

    def test_update_one_profile__sensor(self) -> None:
        """Test case for update_one_profile__sensor

        Update one profile (sensor)
        """
        pass

    def test_update_one_project(self) -> None:
        """Test case for update_one_project

        Update one project
        """
        pass

    def test_update_one_sample__plot(self) -> None:
        """Test case for update_one_sample__plot

        Update one sample (plot)
        """
        pass

    def test_update_one_sensor(self) -> None:
        """Test case for update_one_sensor

        Update one sensor
        """
        pass

    def test_update_one_soil_profile(self) -> None:
        """Test case for update_one_soil_profile

        Update one soil profile
        """
        pass

    def test_update_one_soil_type(self) -> None:
        """Test case for update_one_soil_type

        Update one soil type
        """
        pass

    def test_update_one_transect(self) -> None:
        """Test case for update_one_transect

        Update one transect
        """
        pass


if __name__ == '__main__':
    unittest.main()
