# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.closest_sensor_profile import ClosestSensorProfile

class TestClosestSensorProfile(unittest.TestCase):
    """ClosestSensorProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClosestSensorProfile:
        """Test ClosestSensorProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClosestSensorProfile`
        """
        model = ClosestSensorProfile()
        if include_optional:
            return ClosestSensorProfile(
                distance = 1.337,
                elevation_difference = 1.337,
                id = '',
                name = ''
            )
        else:
            return ClosestSensorProfile(
                distance = 1.337,
                elevation_difference = 1.337,
                id = '',
                name = '',
        )
        """

    def testClosestSensorProfile(self):
        """Test ClosestSensorProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
