# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.plot_sample_update import PlotSampleUpdate

class TestPlotSampleUpdate(unittest.TestCase):
    """PlotSampleUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlotSampleUpdate:
        """Test PlotSampleUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlotSampleUpdate`
        """
        model = PlotSampleUpdate()
        if include_optional:
            return PlotSampleUpdate(
                al_ug_per_g = 1.337,
                archea_per_g = 1.337,
                bacteria_per_g = 1.337,
                c = 1.337,
                ca_ug_per_g = 1.337,
                cl_ug_per_g = 1.337,
                clay_percent = 1.337,
                cn = 1.337,
                fe_ug_per_g = 1.337,
                fungi_per_g = 1.337,
                k_ug_per_g = 1.337,
                loi = 1.337,
                lower_depth_cm = 1.337,
                methanogens_per_g = 1.337,
                methanotrophs_per_g = 1.337,
                mfc = 1.337,
                mg_ug_per_g = 1.337,
                mn_ug_per_g = 1.337,
                n = 1.337,
                na_ug_per_g = 1.337,
                name = '',
                p_ug_per_g = 1.337,
                ph = 1.337,
                plot_id = '',
                replicate = 56,
                rh = 1.337,
                s_ug_per_g = 1.337,
                sample_weight = 1.337,
                sand_percent = 1.337,
                si_ug_per_g = 1.337,
                silt_percent = 1.337,
                subsample_replica_weight = 1.337,
                subsample_weight = 1.337,
                upper_depth_cm = 1.337
            )
        else:
            return PlotSampleUpdate(
        )
        """

    def testPlotSampleUpdate(self):
        """Test PlotSampleUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
