# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.gradientchoices import Gradientchoices

class TestGradientchoices(unittest.TestCase):
    """Gradientchoices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGradientchoices(self):
        """Test Gradientchoices"""
        # inst = Gradientchoices()

if __name__ == '__main__':
    unittest.main()
