# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.soil_profile import SoilProfile

class TestSoilProfile(unittest.TestCase):
    """SoilProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SoilProfile:
        """Test SoilProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SoilProfile`
        """
        model = SoilProfile()
        if include_optional:
            return SoilProfile(
                area_id = '',
                aspect = '',
                coord_srid = 56,
                coord_x = 1.337,
                coord_y = 1.337,
                coord_z = 1.337,
                created_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description_horizon = None,
                gradient = '',
                id = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                lythology_surficial_deposit = '',
                name = '',
                parent_material = 1.337,
                photo = '',
                soil_diagram = '',
                soil_type_id = '',
                topography = '',
                vegetation_type = '',
                weather = ''
            )
        else:
            return SoilProfile(
                area_id = '',
                coord_srid = 56,
                coord_x = 1.337,
                coord_y = 1.337,
                coord_z = 1.337,
                gradient = '',
                id = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                soil_type_id = '',
        )
        """

    def testSoilProfile(self):
        """Test SoilProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
