# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.area_create import AreaCreate

class TestAreaCreate(unittest.TestCase):
    """AreaCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AreaCreate:
        """Test AreaCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AreaCreate`
        """
        model = AreaCreate()
        if include_optional:
            return AreaCreate(
                description = '',
                name = '',
                project_id = ''
            )
        else:
            return AreaCreate(
                project_id = '',
        )
        """

    def testAreaCreate(self):
        """Test AreaCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
