# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.sensor_profile_create import SensorProfileCreate

class TestSensorProfileCreate(unittest.TestCase):
    """SensorProfileCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SensorProfileCreate:
        """Test SensorProfileCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SensorProfileCreate`
        """
        model = SensorProfileCreate()
        if include_optional:
            return SensorProfileCreate(
                area_id = '',
                coord_x = 1.337,
                coord_y = 1.337,
                coord_z = 1.337,
                description = '',
                name = ''
            )
        else:
            return SensorProfileCreate(
                area_id = '',
                name = '',
        )
        """

    def testSensorProfileCreate(self):
        """Test SensorProfileCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
