# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.gnss_create import GnssCreate

class TestGnssCreate(unittest.TestCase):
    """GnssCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GnssCreate:
        """Test GnssCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GnssCreate`
        """
        model = GnssCreate()
        if include_optional:
            return GnssCreate(
                comment = '',
                coord_x = 1.337,
                coord_y = 1.337,
                data_base64 = '',
                elevation_gps = 1.337,
                filename = '',
                latitude = 1.337,
                longitude = 1.337,
                name = '',
                original_filename = '',
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GnssCreate(
        )
        """

    def testGnssCreate(self):
        """Test GnssCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
