# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sensormap_client.models.plot_create import PlotCreate

class TestPlotCreate(unittest.TestCase):
    """PlotCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlotCreate:
        """Test PlotCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlotCreate`
        """
        model = PlotCreate()
        if include_optional:
            return PlotCreate(
                area_id = '',
                aspect = '',
                coord_x = 1.337,
                coord_y = 1.337,
                coord_z = 1.337,
                created_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                gradient = 'flat',
                image = '',
                lithology = '',
                name = '',
                topography = '',
                vegetation_type = '',
                weather = ''
            )
        else:
            return PlotCreate(
                area_id = '',
                coord_x = 1.337,
                coord_y = 1.337,
                coord_z = 1.337,
                gradient = 'flat',
                name = '',
        )
        """

    def testPlotCreate(self):
        """Test PlotCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
