# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Gradientchoices(str, Enum):
    """
    Gradientchoices
    """

    """
    allowed enum values
    """
    FLAT = 'flat'
    SLOPE = 'slope'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Gradientchoices from a JSON string"""
        return cls(json.loads(json_str))


