# coding: utf-8

"""
    soil-api

    API for managing SOIL lab data

    The version of the OpenAPI document: 2.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from sensormap_client.models.gradientchoices import Gradientchoices
from typing import Optional, Set
from typing_extensions import Self

class PlotUpdate(BaseModel):
    """
    PlotUpdate
    """ # noqa: E501
    area_id: Optional[StrictStr] = None
    aspect: Optional[StrictStr] = None
    coord_x: Optional[Union[StrictFloat, StrictInt]] = None
    coord_y: Optional[Union[StrictFloat, StrictInt]] = None
    coord_z: Optional[Union[StrictFloat, StrictInt]] = None
    created_on: Optional[date] = None
    gradient: Optional[Gradientchoices] = None
    image: Optional[StrictStr] = None
    lithology: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    topography: Optional[StrictStr] = None
    vegetation_type: Optional[StrictStr] = None
    weather: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["area_id", "aspect", "coord_x", "coord_y", "coord_z", "created_on", "gradient", "image", "lithology", "name", "topography", "vegetation_type", "weather"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlotUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if area_id (nullable) is None
        # and model_fields_set contains the field
        if self.area_id is None and "area_id" in self.model_fields_set:
            _dict['area_id'] = None

        # set to None if aspect (nullable) is None
        # and model_fields_set contains the field
        if self.aspect is None and "aspect" in self.model_fields_set:
            _dict['aspect'] = None

        # set to None if coord_x (nullable) is None
        # and model_fields_set contains the field
        if self.coord_x is None and "coord_x" in self.model_fields_set:
            _dict['coord_x'] = None

        # set to None if coord_y (nullable) is None
        # and model_fields_set contains the field
        if self.coord_y is None and "coord_y" in self.model_fields_set:
            _dict['coord_y'] = None

        # set to None if coord_z (nullable) is None
        # and model_fields_set contains the field
        if self.coord_z is None and "coord_z" in self.model_fields_set:
            _dict['coord_z'] = None

        # set to None if created_on (nullable) is None
        # and model_fields_set contains the field
        if self.created_on is None and "created_on" in self.model_fields_set:
            _dict['created_on'] = None

        # set to None if gradient (nullable) is None
        # and model_fields_set contains the field
        if self.gradient is None and "gradient" in self.model_fields_set:
            _dict['gradient'] = None

        # set to None if image (nullable) is None
        # and model_fields_set contains the field
        if self.image is None and "image" in self.model_fields_set:
            _dict['image'] = None

        # set to None if lithology (nullable) is None
        # and model_fields_set contains the field
        if self.lithology is None and "lithology" in self.model_fields_set:
            _dict['lithology'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if topography (nullable) is None
        # and model_fields_set contains the field
        if self.topography is None and "topography" in self.model_fields_set:
            _dict['topography'] = None

        # set to None if vegetation_type (nullable) is None
        # and model_fields_set contains the field
        if self.vegetation_type is None and "vegetation_type" in self.model_fields_set:
            _dict['vegetation_type'] = None

        # set to None if weather (nullable) is None
        # and model_fields_set contains the field
        if self.weather is None and "weather" in self.model_fields_set:
            _dict['weather'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlotUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "area_id": obj.get("area_id"),
            "aspect": obj.get("aspect"),
            "coord_x": obj.get("coord_x"),
            "coord_y": obj.get("coord_y"),
            "coord_z": obj.get("coord_z"),
            "created_on": obj.get("created_on"),
            "gradient": obj.get("gradient"),
            "image": obj.get("image"),
            "lithology": obj.get("lithology"),
            "name": obj.get("name"),
            "topography": obj.get("topography"),
            "vegetation_type": obj.get("vegetation_type"),
            "weather": obj.get("weather")
        })
        return _obj


